#
# GitHub and notifications configuration.
# Reference: https://s.apache.org/asfyaml
#
github:
  description: "Website sources for the Apache SIS website"
  homepage: https://sis.apache.org/
  labels:
    - apache
    - sis
    - hugo
    - website
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
